### PR TITLE
add options to set default schema as well as table-specific schema and name

### PR DESCRIPTION
**Pull request by kenfussner**
This addresses Issue #18... allowing users to set the default schema for the DbContexts as well as allows the user to customize the schema and table name for each table individually.  It also allows for additional options to be added in the future w/o causing breaking changes.

While I didn't submit Issue #18, I was actually going to last week before I got pulled away on other work. I, too, would really like to be able to set the schema for the database tables.

### CODE REVIEW

**Comment by scottbrady91** [comment]
Thanks! Will review this soon.

**Comment by brockallen** [comment]
Thanks for this PR. We looked over this and some of it looks good like the `DatabaseTable` approach, but the approach of setting the shared statics on the `Constants` from inside of the `AddConfigurationStore` and `AddOperationalStore` aren't quite the right approach. 

We'd rather see the instance of the `ConfigurationStoreOptions` passed to the `DbContext` ctors and then used inside `OnModelCreating`.

So we can do these changes, or you can take a stab at it. Thoughts?

**Comment by kenfussner** [comment]
Thanks for the feedback! That does sound like a better approach... I'll take a stab at it today or tomorrow.

**Comment by brockallen** [comment]
I think @scottbrady91 might be working on it as we speak. The reason for the rush is that we're trying to get RC2 out tomorrow.

**Comment by scottbrady91** [comment]
I am, yes. Will let you both know when I'm done.

**Comment by kenfussner** [comment]
@brockallen @scottbrady91 check out the latest commit that contains my revision to pass the options into the DbContext ctors instead of using static properties. Let me know how it looks.

**Comment by scottbrady91** [comment]
I was working on a PR to your branch but c4cb454 broke it.

I ended up salvaging some of the work I had done, taking inspiration from this PR, and added this functionality myself.

Thanks for the help though and sorry I couldn't merge this in directly.

**Comment by kenfussner** [comment]
No worries @scottbrady91. I'm just glad to see the functionality in there, and was glad to help out any way that I could.  Thank you for finishing it out!

**Pull request closed without merging**
