### PR TITLE
feat: refactor the token cleanup logic

### PR DESCRIPTION
**Pull request by xyting**
@brockallen @leastprivilege or anyone

 Please review this code. :)

### CODE REVIEW

**Comment by scottbrady91** [comment]
I've made some updates to your PR so that's it's more inline with some of the existing code.

1. I've moved service registration to `UseIdentityServerEfTokenCleanup`. Before this was being done within DI registration which wasn't ideal. I know @MienDev also recommended this and that you tried it before.
2. `TokenCleanupOptions` is now part of `AddOperationalStore` like the other options classes. Feels a bit more 'ASP.NET Core'.
3. The TokenCleanup service is now always registered as part of `AddOperationalStore`. This could be put behind a `TokenCleanupEnabled` bool, but I don't see this being a problem.
4. All test Clients now have a ClientName. I don't know why this wasn't already the case. Seems there's also some truncation going on with the ClientSecrets. I'll open an issue for this.

I still don't like having `IServiceProvider` as a dependency in the TokenCleanup service, but I'm struggling to see an alternative.

Let me know what you think.

**Comment by xyting** [comment]
@scottbrady91
Thanks your review, and good job about the fine tuning. 
yes, 
> I still don't like having IServiceProvider as a dependency in the TokenCleanup service, but I'm struggling to see an alternative.

**Comment by xyting** [comment]
@scottbrady91 
I make a change to use `PersistedGrantDbContext` rather than `IServiceProvider` as a dependency in the `TokenCleanup` service, but I do not know this correct or not because the `PersistedGrantDbContext` is `scoped` lifetime, and this change make the lifetime as long as `TokenCleanup` singleton service.

**Comment by scottbrady91** [comment]
One issue with dee1cc7 and 82b98a6 is that you're holding on to a single `DbContext` for the lifetime of the application. Which isn't good.

I'm struggling to see a solution to this outside of using `IServiceProvider`, as `TokenCleanup` needs to be a singleton in order to register with `IApplicationLifetime` but it needs a new `PersistedGrantDbContext` every operation.

Let's revert to dae4b8f.

**Comment by brockallen** [comment]
@scottbrady91  so is this PR up to snuff and ready to be merged?

**Comment by scottbrady91** [comment]
Yeah, all good

**Comment by brockallen** [comment]
Ok, I'll merge -- but some of it I might want to rework -- not sure why the polling is a middleware now, for example.

**Comment by xyting** [comment]
@brockallen yeah, the polling as a middleware (style) not my initial point.

**Comment by xyting** [comment]
My Wi-Fi is tool poor right now(In China), so I cannot fix the conflicting files

**Comment by brockallen** [comment]
Ok, I looked at the code and I'm ok with registering like other middleware, but I now see it's not actual middleware.

**Comment by brockallen** [comment]
I merged manually, since there were conflicts from my changes this morning.

**Pull request merged**
