### PR TITLE
Create Scoped DbContext instead of resolving dependency from root ServiceProvider

### PR DESCRIPTION
**Pull request by user1336**
Hi,

So in ASP.NET Core 1.1 it is possible to do the following:
```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    return services.BuildServiceProvider(validateScopes: true);
}
```

Setting this parameter to true will validate the correct lifetime of the dependencies. 
This gave a few errors in the Stores namespace. The DbContexts are registered as Scoped services (which is good) but are being resolved from the root ServiceProvider context which means the dependency will be Singleton. This means that the connection to the DbContext will remain open for the current request.

Now we create a Scoped service within the Transient dependency.

### CODE REVIEW

**Comment by user1336** [comment]
Sorry for breaking the tests, I hope to fix them soon.

**Comment by brockallen** [comment]
I'm confused why this is necessary? Shouldn't the dependency be scoped already based on DI config?

**Comment by user1336** [comment]
The root service provider is not a scoped instance. It's a transient service, which causes the DbContext services to be resolved as transient as well. You can check this with the code provided in the first post.

**Comment by brockallen** [comment]
I've not spent too much time on this, but after my cursory look at it I guess my concern is that creating this scope manually seems wrong to me. Do you have another suggestion to address this at the DI level?

**Comment by brockallen** [comment]
> but are being resolved from the root ServiceProvider context

Did you ever determine where?

**Comment by brockallen** [comment]
Also, I just made this targeted change: https://github.com/IdentityServer/IdentityServer4.EntityFramework/issues/56#issuecomment-287637969

Perhaps that was the only place you encountered the scope mismatch?

**Comment by user1336** [comment]
To answer your where question: In the different Stores and the CorsPolicyService (which you fixed).
There were actually four places were I encountered the scope mismatch, I guess the issue still persists.

I'm ok with closing the PR since I agree on you that manually creating the scope isn't probably the most beautiful solution..

**Pull request closed without merging**
