### PR TITLE
Decouple the the configuration for automapper  with `Profile`

### PR DESCRIPTION
**Pull request by MienDev**
Decouple the the configuration for automapper  with `Profile`

### CODE REVIEW

**Comment by MienDev** [comment]
A separated config class can be used by other assemblies,  such as one for ConfigrationAdminStore,  also can be user for DI in asp.net core where the config can be resisted as static, but using the mapper as instance。

**Comment by scottbrady91** [comment]
Thanks. Can you describe why this PR would be useful to implementors? What are the use cases for this?

**Comment by MienDev** [comment]
well, @scottbrady91  thanks for your reply :) 
Sorry for that,  I have not asked for preceding comment for this, and  just submitted this pull request.  :) 

Story began from,  I wanna to implement an IdentityServer ConfigrationAdminStore,  through which I manage the `scope` and `client` for CURD as administrator.

Take this scenario,  I wanna to **patch a scope**,  using automapper.

```c#
// Step 1. 
// Generate a model from Front-End changes. (using JsonPatchDocument)
// There could be palatially updated properties for a scope. 
var scopeModel = new scopeModel{ name =profile ,  required =true } 

// Step 2.
// get the original scopeEntity
var scopeEnitity = _ctx.GetSopeByName(scopeModel)

// Step 3.
// var  mapperconfig =  scopeMapperConfig.AddProfile( profileSomePropertiesExcluded)
// var _mapper = mapperconfig.CreateMapper();
// e.g  I exclude the `scopeSecret` property. 
_mapper.map(scopeModel, scopeEntity)
// _ctx.SaveChanges();
```
In step 3, I **use a customized automapper configuration**, but not `scope.ToEntity()`. 

Take this as an example, In some scenarios: 
- There could be **more than one mapper configurations** in a whole solution. 
-  If I want to **map a model for all properties using a `_mapper.map(a,b)` style**, I need to create a `profile` that is the same as the config that `toEntity()` extension method used.).  In fact I could reuse the configure for the same mapping. 

**Benefits  after the changes**:
- Reusable (use not only with a extension method.)
- Uniform Style  (all auto mapper config in profile.)
- Compatible with DI. ( someone loves DI)

yeah, I don't know if this convincing for you. 
but no bad for the code, just provided more options for implementer :)

**Comment by MienDev** [comment]
closed this since no response.

**Comment by scottbrady91** [comment]
I haven't had chance to review this yet. Bear with us.

**Comment by MienDev** [comment]
yeah, take it easy and take your time.  This PR is just optional for some others.
It's absolutely more important for the 1.0 RTM version of IDS4, waiting for that. 
Thanks to you and the team again.

**Comment by brockallen** [comment]
Also, @scottbrady91, can we check this one -- I want to release rc3 today if possible.

**Comment by brockallen** [comment]
ok, done. thanks

**Pull request merged**
